from building import *

cwd = GetCurrentDir()

# add the asm test drivers.
src     = []
if  GetDepend('BSP_USING_ASMTEST'):
    src += ['asm_test_cmd.c']
    src += ['asm_test.s']

    group = DefineGroup('Asmtest', src, depend = [''])

Return('group')
