from building import *
import os

cwd     = GetCurrentDir()
CPPPATH = [cwd]

src = Split("""
main.c
slcd.c
""")

if  GetDepend('BSP_USING_ASMTEST'):
    src += ['asm_test/asm_test_cmd.c']
    src += ['asm_test/asm_test.s']

src += ['fxls8974/fxls8974.c']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
